### PR TITLE
Make timezone configurable

### PR DESCRIPTION
**Pull request by pauloconnor**
Move the timezone configuration out of the baked in config file to a variable in the params manifest.

### CODE REVIEW

**Comment by electrical** [comment]
My reason for supplying a static file instead of a template is to let people create there own complete configuration file instead of being dependent on the template i provide.
Second reason is that for all config options i would need to create variables in the init file to pass down to the template.

Using a static file via the "puppet:///" way simplifies the module and saves allot of work for me and the user experience.

What are your idea's on this with my arguments?

**Comment by pauloconnor** [comment]
My thinking here is that the timezone is the only option currently used in that config file as it stands. While I understand your approach, I'm thinking more along the lines of having sensible defaults that are easily changed. With Graphite, timezone is important as the whisper files are marked with that TZ upon creation and it's difficult to change them later. Having an obvious parameter to change, this situation should be more easily avoided.

**Comment by zebpalmer** [comment]
yeah, I would agree. In most cases timezone would be the only thing there that is changed. the pull request looks sane to me, I'll be pulling it into my copy.

side note:  I've been installing via pip, carbon and whisper are in Ubuntu's repos (didn't notice version) but I haven't seen graphite-web. Am I missing a current ppa somewhere?

**Comment by electrical** [comment]
Hi,

Sorry i haven't responded in a while on this.
I'll need to take a better look at this because it will need to work in both debian and redhat os'.
Will get back about this.

in regards graphite-web not being in pip, it should be there.. can't check the current name though.

**Comment by zebpalmer** [comment]
sorry, I know it's in pip, I was asking about an ubuntu repo... I only took a quick glance at the module source but I thought it required graphite to be accessible in the apt repo. I'll look again.

**Comment by electrical** [comment]
@zebpalmer  Ahh okay. sorry. was very early when I've read it.
My current module assumes its in a repo yeah.
Downside of using the pip installs is that there are no init files ( i can create them of course )

In any case i will need to review the whole module anyway as its only really working on CentOS ( initially developed it for that ) and not directly on Debian/Ubuntu.

Any idea's are always welcome :-)

**Pull request closed without merging**
